version: "3.8"

services:
  frontend:
    build: ./example-frontend
    image: part1-frontend
    ports:
      - "5000:5000"
  redis:
    image: redis:7.0.8-alpine
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
  backend:
    build: ./example-backend
    environment:
      - REDIS_HOST=redis
    image: part1-backend
    ports:
      - "8080:8080"