version: "3.8"

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    container_name: db_postgres
    environment:
      POSTGRES_PASSWORD: salasana123
    volumes:
      - data:/var/lib/postgresql/data

  frontend:
    build: ../examples/example-frontend
    image: part1-frontend

  redis:
    image: redis:7.0.8-alpine
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: ../examples/example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=salasana123
    image: part1-backend
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  data: