version: "3.8"

services:
  frontend:
    build: ../examples/example-frontend
    image: part1-frontend
    ports:
      - "5000:5000"
  backend:
    build: ../examples/example-backend
    image: part1-backend
    ports:
      - "8080:8080"