version: '3.9'

services:
  frontend:
    build: ../examples/ml-kurkkumopo-frontend
    ports:
      - "3000:3000"
  backend:
    build: ../examples/ml-kurkkumopo-backend
    ports:
      - "5000:5000"
    volumes:
      - training-model:/src/model
  training:
    build: ../examples/ml-kurkkumopo-training
    volumes:
      - training-model:/src/model
      - training-data:/src/data
volumes:
  training-model:
  training-data:


